# Generated by Django 4.2.5 on 2023-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_category_actors_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'ordering': ['-crt_time', 'title'], 'verbose_name': 'актёров', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.ImageField(upload_to='photos%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
