# Generated by Django 4.2.5 on 2023-10-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actors_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
